# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_SLEEP=y

# These are troubleshooting items
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_ZMK_BLE_PASSKEY_ENTRY=n


CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

# Left-thumb  orientation by default.
#CONFIG_PMW3610_ALT_SWAP_XY=y
CONFIG_PMW3610_ALT_INVERT_X=y
#CONFIG_PMW3610_ALT_INVERT_Y=y

# CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12
#CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=2000
#// <--see Troubleshooting


# Set max number of BT connections
CONFIG_BT_MAX_CONN=8
CONFIG_BT_MAX_PAIRED=8


CONFIG_ZMK_KEYBOARD_NAME="Trackball v.4"
